name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev build-essential

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: build
        run: |
          cargo build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gtk4-rs-test
          if-no-files-found: error
          path: target/release/gtk4-rs-test
